[application]

# App (Project) Name
name = "family_manage"

# Dioxus App Default Platform
# desktop, web
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (public) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = "family_manage"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# if miss this property, the router will lose efficacy
index_on_404 = true
# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["tailwind.css", "/src/base.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[[web.proxy]]
backend = "http://localhost:8000/api/"
